//! The contract between agent adapters and the daemon.
//!
//! An adapter turns one agent's native payloads (hook calls, log lines) into
//! [`Event`]s. Adapters are pure translation: they never touch the network,
//! the database or the privacy policy. The daemon owns all of that, which is
//! why raw payloads can be kept and re-normalized when an adapter improves.

use std::path::PathBuf;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use uuid::Uuid;

use crate::Event;

/// A raw agent payload, stamped at the moment the agent emitted it. Hooks run
/// out-of-process and may be spooled, so the timestamp must be taken by the
/// hook itself rather than by the daemon.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HookEnvelope {
    /// Generated by the hook. Adapters derive event ids from it, so a
    /// redelivered envelope never produces duplicate events.
    pub id: Uuid,
    pub observed_at: DateTime<Utc>,
    pub payload: Value,
}

/// The result of normalizing one hook payload.
#[derive(Debug, Default)]
pub struct Normalized {
    pub events: Vec<Event>,
    /// Transcript files that may have new lines for [`Adapter::parse_transcript_line`].
    pub transcripts: Vec<String>,
}

pub trait Adapter: Send + Sync {
    /// Stable identifier, used in URLs (`/v1/adapters/{name}`), the CLI and `agent.name`.
    fn name(&self) -> &'static str;

    /// Translates one hook payload. Payloads that aren't recognizable produce no events.
    fn normalize(&self, envelope: &HookEnvelope) -> Normalized;

    /// Translates one line of a transcript named in [`Normalized::transcripts`].
    /// Must be deterministic: the same line always yields the same event id.
    fn parse_transcript_line(&self, trajectory_id: &str, line: &str) -> Option<Event> {
        let _ = (trajectory_id, line);
        None
    }

    /// Directories this adapter's transcripts may live in. Transcript paths
    /// arrive inside payloads, so the daemon refuses to open anything else.
    fn transcript_roots(&self) -> Vec<PathBuf> {
        Vec::new()
    }
}
