// Ground Station extension for pi (https://pi.dev).
// groundstation-extension: pi
//
// Generated by `groundstation connect pi`; `groundstation disconnect pi`
// removes it. Edits are overwritten on reconnect.
//
// Forwards pi's session, run, model and tool events to the local Ground
// Station daemon (gsd). Bulky fields (system prompts, message content,
// images) are dropped here; privacy rules are applied by gsd. If gsd is
// unreachable, events are handed to `groundstation hook pi`, which spools
// them to disk until gsd is back. Nothing is ever printed.

import { spawn } from "node:child_process";
import { existsSync, readFileSync, realpathSync } from "node:fs";
import { dirname, join } from "node:path";

const GSD_URL = "__GSD_URL__";
const GROUNDSTATION = "__GROUNDSTATION__";

/** pi's own version, found by walking up from the running script. */
function piVersion() {
  try {
    let dir = dirname(realpathSync(process.argv[1]));
    for (let i = 0; i < 8; i++) {
      const manifest = join(dir, "package.json");
      if (existsSync(manifest)) {
        const pkg = JSON.parse(readFileSync(manifest, "utf8"));
        if (pkg.name === "@earendil-works/pi-coding-agent") return pkg.version;
      }
      dir = dirname(dir);
    }
  } catch {}
  return undefined;
}

const VERSION = piVersion();

function textOf(content) {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return undefined;
  const text = content.filter((c) => c && c.type === "text").map((c) => c.text);
  return text.length ? text.join("\n") : undefined;
}

/** Keeps only scalar fields, so tool details never carry large blobs. */
function scalars(obj) {
  if (!obj || typeof obj !== "object") return undefined;
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v === null || ["string", "number", "boolean"].includes(typeof v)) out[k] = v;
  }
  return out;
}

function spool(payload) {
  try {
    const child = spawn(GROUNDSTATION, ["hook", "pi"], { stdio: ["pipe", "ignore", "ignore"] });
    child.on("error", () => {});
    child.stdin.on("error", () => {});
    child.stdin.end(JSON.stringify(payload));
  } catch {}
}

async function send(payload) {
  const envelope = { id: crypto.randomUUID(), observed_at: new Date().toISOString(), payload };
  try {
    const res = await fetch(`${GSD_URL}/v1/adapters/pi`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(envelope),
      signal: AbortSignal.timeout(2000),
    });
    // 422: gsd understood the request but not the payload; retrying won't help.
    if (res.ok || res.status === 422) return;
  } catch {}
  spool(payload);
}

function forward(event, ctx) {
  try {
    const session = ctx.sessionManager?.getSessionId?.();
    if (!session) return;
    void send({
      event,
      // Stable across the fetch and spool paths, so gsd never double-counts.
      event_id: crypto.randomUUID(),
      at: Date.now(),
      session_id: session,
      cwd: ctx.cwd,
      version: VERSION,
    });
  } catch {}
}

export default function (pi) {
  pi.on("session_start", (e, ctx) => forward({ type: e.type, reason: e.reason }, ctx));
  pi.on("session_shutdown", (e, ctx) => forward({ type: e.type, reason: e.reason }, ctx));
  pi.on("before_agent_start", (e, ctx) => forward({ type: e.type, prompt: e.prompt }, ctx));
  pi.on("agent_end", (e, ctx) => {
    const last = [...(e.messages ?? [])].reverse().find((m) => m?.role === "assistant");
    forward({ type: e.type, stopReason: last?.stopReason, errorMessage: last?.errorMessage }, ctx);
  });
  pi.on("message_end", (e, ctx) => {
    const m = e.message;
    if (m?.role !== "assistant") return;
    forward(
      {
        type: e.type,
        message: {
          provider: m.provider,
          model: m.model,
          responseModel: m.responseModel,
          responseId: m.responseId,
          usage: m.usage,
          stopReason: m.stopReason,
          errorMessage: m.errorMessage,
          timestamp: m.timestamp,
          toolCalls: Array.isArray(m.content) ? m.content.filter((c) => c?.type === "toolCall").length : 0,
        },
        // The message is stamped when streaming starts; this is when it ended.
        durationMs: typeof m.timestamp === "number" ? Math.max(0, Date.now() - m.timestamp) : undefined,
      },
      ctx,
    );
  });
  pi.on("tool_execution_start", (e, ctx) =>
    forward({ type: e.type, toolCallId: e.toolCallId, toolName: e.toolName, args: e.args }, ctx),
  );
  pi.on("tool_execution_end", (e, ctx) =>
    forward(
      {
        type: e.type,
        toolCallId: e.toolCallId,
        toolName: e.toolName,
        isError: e.isError,
        output: textOf(e.result?.content),
        details: scalars(e.result?.details),
      },
      ctx,
    ),
  );
  pi.on("session_compact", (e, ctx) =>
    forward({ type: e.type, reason: e.reason, willRetry: e.willRetry }, ctx),
  );
}
