//! Types exchanged over gsd's local HTTP API (shared with the `groundstation` CLI).

use chrono::{DateTime, Utc};
use groundstation_schema::{Batch, Event};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use uuid::Uuid;

/// A raw agent payload, stamped at the moment the agent emitted it. Hooks run
/// out-of-process and may be spooled, so the timestamp must be taken by the
/// hook itself rather than by the daemon.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HookEnvelope {
    /// Generated by the hook; event ids are derived from it, so a redelivered
    /// envelope never produces duplicate events.
    pub id: Uuid,
    pub observed_at: DateTime<Utc>,
    pub payload: Value,
}

/// What the hook writes to the spool directory when the daemon is unreachable.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", content = "body", rename_all = "kebab-case")]
pub enum SpoolItem {
    ClaudeCode(HookEnvelope),
    Batch(Batch),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IngestResponse {
    /// Events produced by this request that were new or changed.
    pub stored: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Health {
    pub status: String,
    pub version: String,
    pub schema: String,
    pub pid: u32,
    pub data_dir: String,
    pub trajectories: u64,
    pub events: u64,
    pub spool_pending: usize,
    pub upload: UploadStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UploadStatus {
    /// `local-only` or `cloud`.
    pub mode: String,
    /// `None` in local-only mode.
    pub endpoint: Option<String>,
    pub pending: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrajectorySummary {
    pub id: String,
    pub agent: String,
    pub agent_version: Option<String>,
    pub title: Option<String>,
    pub status: String,
    pub cwd: Option<String>,
    pub repository: Option<String>,
    pub branch: Option<String>,
    pub host: Option<String>,
    pub started_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub ended_at: Option<DateTime<Utc>>,
    pub duration_ms: i64,
    pub event_count: u64,
    pub user_turns: u64,
    pub model_calls: u64,
    pub tool_calls: u64,
    pub tool_errors: u64,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_read_tokens: u64,
    pub cache_creation_tokens: u64,
}

impl TrajectorySummary {
    /// Every token the model processed or produced, cached or not.
    pub fn total_tokens(&self) -> u64 {
        self.input_tokens + self.output_tokens + self.cache_read_tokens + self.cache_creation_tokens
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrajectoryDetail {
    #[serde(flatten)]
    pub summary: TrajectorySummary,
    pub events: Vec<Event>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrorBody {
    pub error: String,
}
