// Ground Station plugin for OpenCode v2.
// groundstation-plugin: opencode
//
// Generated by `groundstation connect opencode`; `groundstation disconnect
// opencode` removes it. Edits are overwritten on reconnect.
//
// Forwards OpenCode's session events to the local Ground Station daemon (gsd).
// Events are sent as-is apart from dropping bulky fields (attachments,
// provider state, compaction text); privacy rules are applied by gsd.
// If gsd is unreachable, events are handed to `groundstation hook opencode`,
// which spools them to disk until gsd is back. Nothing is ever printed.

import { spawn } from "node:child_process";

const GSD_URL = "__GSD_URL__";
const GROUNDSTATION = "__GROUNDSTATION__";

const FORWARD = new Set([
  "session.created",
  "session.deleted",
  "session.inbox.enqueued",
  "session.execution.succeeded",
  "session.execution.failed",
  "session.execution.interrupted",
  "session.step.ended",
  "session.step.failed",
  "session.tool.called",
  "session.tool.success",
  "session.tool.failed",
  "session.compaction.started",
  "session.compaction.ended",
  "permission.asked",
]);

// State the adapter can't derive from a single event.
const parents = new Map(); // sessionID -> parentID
const toolNames = new Map(); // tool call id -> tool name
const steps = new Map(); // assistantMessageID -> { model, agent, started }

function rootOf(sessionID) {
  let id = sessionID;
  for (let hops = 0; parents.has(id) && hops < 32; hops++) id = parents.get(id);
  return id;
}

function textOnly(content) {
  return Array.isArray(content) ? content.filter((c) => c && c.type === "text") : undefined;
}

// Returns the payload to forward, or undefined to skip the event.
function prepare(event, context) {
  const data = { ...(event.data ?? {}) };
  const extra = {};
  switch (event.type) {
    case "session.created":
      if (data.parentID) parents.set(data.sessionID, data.parentID);
      delete data.permissions;
      break;
    case "session.inbox.enqueued":
      if (data.item?.type !== "user") return undefined;
      data.item = { type: "user", payload: { text: data.item.payload?.text ?? "" } };
      break;
    case "session.step.ended":
    case "session.step.failed": {
      const step = steps.get(data.assistantMessageID);
      steps.delete(data.assistantMessageID);
      if (step) extra.step = step;
      delete data.providerState;
      break;
    }
    case "session.tool.called":
      extra.tool = toolNames.get(data.id);
      delete data.state;
      break;
    case "session.tool.success":
    case "session.tool.failed":
      extra.tool = toolNames.get(data.id);
      toolNames.delete(data.id);
      data.content = textOnly(data.content);
      delete data.resultState;
      break;
    case "session.compaction.ended":
      delete data.text;
      delete data.recent;
      delete data.providerState;
      delete data.providerContext;
      break;
  }
  const sessionID = data.sessionID;
  return {
    event: { id: event.id, created: event.created, type: event.type, location: event.location, data },
    ...extra,
    root_session_id: sessionID ? rootOf(sessionID) : undefined,
    ...context,
  };
}

function observe(event) {
  const data = event.data ?? {};
  if (event.type === "session.tool.input.started") toolNames.set(data.id, data.name);
  if (event.type === "session.step.started") {
    steps.set(data.assistantMessageID, { model: data.model, agent: data.agent, started: data.started });
  }
}

function spool(payload) {
  try {
    const child = spawn(GROUNDSTATION, ["hook", "opencode"], { stdio: ["pipe", "ignore", "ignore"] });
    child.on("error", () => {});
    child.stdin.on("error", () => {});
    child.stdin.end(JSON.stringify(payload));
  } catch {}
}

async function send(payload) {
  const envelope = { id: crypto.randomUUID(), observed_at: new Date().toISOString(), payload };
  try {
    const res = await fetch(`${GSD_URL}/v1/adapters/opencode`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(envelope),
      signal: AbortSignal.timeout(2000),
    });
    // 422: gsd understood the request but not the payload; retrying won't help.
    if (res.ok || res.status === 422) return;
  } catch {}
  spool(payload);
}

export default {
  id: "groundstation",
  setup(ctx) {
    const controller = new AbortController();
    // Sent with every event: session.created can precede the subscription.
    const context = { directory: ctx.location?.directory, version: ctx.app?.version };
    void (async () => {
      for await (const event of ctx.event.subscribe({ signal: controller.signal })) {
        try {
          observe(event);
          if (!FORWARD.has(event.type)) continue;
          const payload = prepare(event, context);
          if (payload) void send(payload);
        } catch {}
      }
    })().catch(() => {});
    return () => controller.abort();
  },
};
